### PR TITLE
Add DIMC and CGRA blocks

### PR DESCRIPTION
**Pull request by rgantonio**
This PR adds the DIMC and CGRA modules.

Major TODO:
- [x] Add DIMC
- [x] Add CGRA
- [x] Add to hemaia config
- [x] Check if test builds correctly

NOTE:
There is a big problem with the CGRA built with HLS. The SV constructs for pack and unpacked ports are not valid for Verilator. It only works for Questa. I verified that the CGRA builds and synthesizes (got results for it). But Verilator itself does not compile. This should work though.

### CODE REVIEW

**Comment by rgantonio** [comment]
Bump @Konste11ation and @IveanEx 

@Konste11ation when you synthesize, could you please use the `hemaia_tapeout.hjson` configuration. That one has all four proper clusters 😄 

Also before doing `compile_ultra` could we both look at the library setup first just to be sure.

**Comment by Konste11ation** [comment]
> Bump @Konste11ation and @IveanEx
> 
> @Konste11ation when you synthesize, could you please use the `hemaia_tapeout.hjson` configuration. That one has all four proper clusters 😄
> 
> Also before doing `compile_ultra` could we both look at the library setup first just to be sure.

Okie. After passing the CI I will try to run the synthesis with 4 clusters and the extra 32 GPIO pads.

**Review by Konste11ation — APPROVED** [review]

**Review by IveanEx — APPROVED** [review]
Since all bugs are fixed, I will approve this PR! 🥳🥳

**Comment by rgantonio** [comment]
Thanks @Konste11ation and @IveanEx !

**Pull request merged**
